# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ae704ec621afb917c93bfe53b5b90047383ad8be9671f51c42168590e89de9a80f974203825f08745119142aee1266518d5ca49065ca08465f3d4dc645ad6ad

test:
  secret_key_base: 06265ef66d67ff1edee7ec2389c4773c95f47c35352af4440bf9df1dbd80d54b26aa68e008baacea21039cd06e0ffe50b602f3d13954dfb66d2bfcfeacea1b80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
